name: Verify OpenShift YAML Syntax

on:
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  verify-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install OpenShift CLI
      - name: Install OpenShift CLI
        run: |
          curl -L https://downloads-openshift-console.apps.sandbox-m3.1530.p1.openshiftapps.com/amd64/linux/oc.tar
          tar -xvzf oc.tar
          sudo mv oc /usr/local/bin/oc

      # Optionally Install yamllint for YAML syntax check
      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      # Lint YAML files using yamllint
      - name: YAML Lint
        run: yamllint .

      # Validate YAML with oc to ensure OpenShift syntax is correct
      - name: OpenShift YAML Validation
        run: |
          for file in $(find . -name "*.yaml" -o -name "*.yml"); do
            echo "Validating $file"
            oc apply --dry-run=client -f "$file"
          done
